tree <- empty_search_tree()
for (i in 1:10)
  tree <- insert(tree, i)
plot(tree)

tree <- empty_red_black_tree()
for (i in 1:10)
  tree <- insert(tree, i)
plot(tree)

heap <- empty_leftist_heap()
for (i in 1:15)
  heap <- insert(heap, i)
plot(heap)

heap <- empty_splay_heap()
for (i in 1:15)
  heap <- insert(heap, i)
plot(heap)

heap <- delete_minimal(heap)
plot(heap)
heap <- delete_minimal(heap)
plot(heap)
heap <- delete_minimal(heap)
plot(heap)
heap <- delete_minimal(heap)
plot(heap)
heap <- delete_minimal(heap)
plot(heap)

heap <- empty_binomial_heap()
for (i in 1:15)
  heap <- insert(heap, i)
plot(heap)

